/**
 * launchUtils.test.ts
 *
 * Tests for isNonSteamShortcut() and launchTypeFor() – the functions that
 * classify a Steam appId and select the correct RunGame launch type.
 *
 * Game-type coverage:
 *   - Native Linux games    (appId < 0x80000000, launchType = 100)
 *   - Proton games          (appId < 0x80000000, launchType = 100)
 *   - Non-Steam shortcuts   (appId >= 0x80000000, launchType = 104)
 */

import {
  NON_STEAM_APPID_THRESHOLD,
  LAUNCH_TYPE_DEFAULT,
  LAUNCH_TYPE_GAME,
  LAUNCH_TYPE_SHORTCUT,
  isNonSteamShortcut,
  launchTypeFor,
} from "../utils/launchUtils";

// ------------------------------------------------------------------ //
// isNonSteamShortcut                                                   //
// ------------------------------------------------------------------ //

describe("isNonSteamShortcut", () => {
  describe("Steam games (should return false)", () => {
    const steamGames: [string, number][] = [
      ["Half-Life 2 (native Linux)", 220],
      ["Team Fortress 2 (native Linux)", 440],
      ["Dota 2 (native Linux)", 570],
      ["Cyberpunk 2077 (Proton)", 1091500],
      ["Elden Ring (Proton)", 1245620],
      ["appId just below threshold", NON_STEAM_APPID_THRESHOLD - 1],
    ];

    it.each(steamGames)("%s – appId %i", (_name, appId) => {
      expect(isNonSteamShortcut(appId)).toBe(false);
    });
  });

  describe("Non-Steam shortcuts (should return true)", () => {
    const shortcuts: [string, number][] = [
      ["exactly at threshold", NON_STEAM_APPID_THRESHOLD],
      ["threshold + 1", NON_STEAM_APPID_THRESHOLD + 1],
      ["typical generated shortcut id", NON_STEAM_APPID_THRESHOLD + 123456],
      ["near uint32 max", 0xffffff00],
    ];

    it.each(shortcuts)("%s – appId %i", (_name, appId) => {
      expect(isNonSteamShortcut(appId)).toBe(true);
    });
  });
});

// ------------------------------------------------------------------ //
// launchTypeFor                                                        //
// ------------------------------------------------------------------ //

describe("launchTypeFor", () => {
  describe("native Linux games → LAUNCH_TYPE_GAME (100)", () => {
    it("Half-Life 2 (220)", () => {
      expect(launchTypeFor(220)).toBe(LAUNCH_TYPE_GAME);
    });

    it("Team Fortress 2 (440)", () => {
      expect(launchTypeFor(440)).toBe(LAUNCH_TYPE_GAME);
    });

    it("Dota 2 (570)", () => {
      expect(launchTypeFor(570)).toBe(LAUNCH_TYPE_GAME);
    });
  });

  describe("Proton games → LAUNCH_TYPE_GAME (100)", () => {
    // Proton games have normal Steam appIds; the Proton layer is chosen
    // by Steam automatically based on the user's compatibility settings.
    it("Cyberpunk 2077 (1091500)", () => {
      expect(launchTypeFor(1091500)).toBe(LAUNCH_TYPE_GAME);
    });

    it("Elden Ring (1245620)", () => {
      expect(launchTypeFor(1245620)).toBe(LAUNCH_TYPE_GAME);
    });

    it("GTA V (271590)", () => {
      expect(launchTypeFor(271590)).toBe(LAUNCH_TYPE_GAME);
    });
  });

  describe("non-Steam shortcuts → LAUNCH_TYPE_SHORTCUT (104)", () => {
    it("appId at threshold", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD)).toBe(LAUNCH_TYPE_SHORTCUT);
    });

    it("typical generated shortcut id", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD + 99999)).toBe(LAUNCH_TYPE_SHORTCUT);
    });
  });

  describe("constant values are correct", () => {
    it("LAUNCH_TYPE_DEFAULT is -1", () => {
      expect(LAUNCH_TYPE_DEFAULT).toBe(-1);
    });

    it("LAUNCH_TYPE_GAME is 100", () => {
      expect(LAUNCH_TYPE_GAME).toBe(100);
    });

    it("LAUNCH_TYPE_SHORTCUT is 104", () => {
      expect(LAUNCH_TYPE_SHORTCUT).toBe(104);
    });

    it("NON_STEAM_APPID_THRESHOLD is 0x80000000", () => {
      expect(NON_STEAM_APPID_THRESHOLD).toBe(0x80000000);
    });
  });

  describe("RunGame argument mapping (regression)", () => {
    // Steam's RunGame(appId, "", launchOptionIndex, launchType) —
    // arg 3 is always LAUNCH_TYPE_DEFAULT (-1),
    // arg 4 is what launchTypeFor() returns.

    it("Steam game gets LAUNCH_TYPE_GAME (100) for arg 4", () => {
      // Cyberpunk 2077 — a well-known Proton title
      expect(launchTypeFor(1091500)).toBe(LAUNCH_TYPE_GAME);
    });

    it("non-Steam shortcut gets LAUNCH_TYPE_SHORTCUT (104) for arg 4", () => {
      // Realistic appId generated by Steam for a non-Steam shortcut.
      // Steam generates these via CRC32 of the exe path, always >= 0x80000000.
      const realisticShortcutId = 0x80000000 + 0x1a2b3c; // 2 148 718 652
      expect(launchTypeFor(realisticShortcutId)).toBe(LAUNCH_TYPE_SHORTCUT);
    });

    it("boundary: last Steam appId (0x7FFFFFFF) → LAUNCH_TYPE_GAME", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD - 1)).toBe(LAUNCH_TYPE_GAME);
    });

    it("boundary: first non-Steam appId (0x80000000) → LAUNCH_TYPE_SHORTCUT", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD)).toBe(LAUNCH_TYPE_SHORTCUT);
    });
  });
});
