/**
 * launchUtils.test.ts
 *
 * Tests for isNonSteamShortcut() and launchTypeFor() – the functions that
 * classify a Steam appId and select the correct RunGame launch type.
 *
 * Game-type coverage:
 *   - Native Linux games    (appId < 0x80000000, launchType = 100)
 *   - Proton games          (appId < 0x80000000, launchType = 100)
 *   - Non-Steam shortcuts   (appId >= 0x80000000, launchType = 104)
 */

import {
  NON_STEAM_APPID_THRESHOLD,
  LAUNCH_TYPE_DEFAULT,
  LAUNCH_TYPE_GAME,
  LAUNCH_TYPE_SHORTCUT,
  isNonSteamShortcut,
  launchTypeFor,
  toUnsignedAppId,
} from "../utils/launchUtils";

// ------------------------------------------------------------------ //
// isNonSteamShortcut                                                   //
// ------------------------------------------------------------------ //

describe("isNonSteamShortcut", () => {
  describe("Steam games (should return false)", () => {
    const steamGames: [string, number][] = [
      ["Half-Life 2 (native Linux)", 220],
      ["Team Fortress 2 (native Linux)", 440],
      ["Dota 2 (native Linux)", 570],
      ["Cyberpunk 2077 (Proton)", 1091500],
      ["Elden Ring (Proton)", 1245620],
      ["appId just below threshold", NON_STEAM_APPID_THRESHOLD - 1],
    ];

    it.each(steamGames)("%s – appId %i", (_name, appId) => {
      expect(isNonSteamShortcut(appId)).toBe(false);
    });
  });

  describe("Non-Steam shortcuts (should return true)", () => {
    const shortcuts: [string, number][] = [
      ["exactly at threshold", NON_STEAM_APPID_THRESHOLD],
      ["threshold + 1", NON_STEAM_APPID_THRESHOLD + 1],
      ["typical generated shortcut id", NON_STEAM_APPID_THRESHOLD + 123456],
      ["near uint32 max", 0xffffff00],
    ];

    it.each(shortcuts)("%s – appId %i", (_name, appId) => {
      expect(isNonSteamShortcut(appId)).toBe(true);
    });
  });
});

// ------------------------------------------------------------------ //
// launchTypeFor                                                        //
// ------------------------------------------------------------------ //

describe("launchTypeFor", () => {
  describe("native Linux games → LAUNCH_TYPE_GAME (100)", () => {
    it("Half-Life 2 (220)", () => {
      expect(launchTypeFor(220)).toBe(LAUNCH_TYPE_GAME);
    });

    it("Team Fortress 2 (440)", () => {
      expect(launchTypeFor(440)).toBe(LAUNCH_TYPE_GAME);
    });

    it("Dota 2 (570)", () => {
      expect(launchTypeFor(570)).toBe(LAUNCH_TYPE_GAME);
    });
  });

  describe("Proton games → LAUNCH_TYPE_GAME (100)", () => {
    // Proton games have normal Steam appIds; the Proton layer is chosen
    // by Steam automatically based on the user's compatibility settings.
    it("Cyberpunk 2077 (1091500)", () => {
      expect(launchTypeFor(1091500)).toBe(LAUNCH_TYPE_GAME);
    });

    it("Elden Ring (1245620)", () => {
      expect(launchTypeFor(1245620)).toBe(LAUNCH_TYPE_GAME);
    });

    it("GTA V (271590)", () => {
      expect(launchTypeFor(271590)).toBe(LAUNCH_TYPE_GAME);
    });
  });

  describe("non-Steam shortcuts → LAUNCH_TYPE_SHORTCUT (104)", () => {
    it("appId at threshold", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD)).toBe(LAUNCH_TYPE_SHORTCUT);
    });

    it("typical generated shortcut id", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD + 99999)).toBe(LAUNCH_TYPE_SHORTCUT);
    });
  });

  describe("constant values are correct", () => {
    it("LAUNCH_TYPE_DEFAULT is -1", () => {
      expect(LAUNCH_TYPE_DEFAULT).toBe(-1);
    });

    it("LAUNCH_TYPE_GAME is 100", () => {
      expect(LAUNCH_TYPE_GAME).toBe(100);
    });

    it("LAUNCH_TYPE_SHORTCUT is 104", () => {
      expect(LAUNCH_TYPE_SHORTCUT).toBe(104);
    });

    it("NON_STEAM_APPID_THRESHOLD is 0x80000000", () => {
      expect(NON_STEAM_APPID_THRESHOLD).toBe(0x80000000);
    });
  });

  describe("RunGame argument mapping (regression)", () => {
    // Steam's RunGame(appId, "", launchOptionIndex, launchType) —
    // arg 3 is always LAUNCH_TYPE_DEFAULT (-1),
    // arg 4 is what launchTypeFor() returns.

    it("Steam game gets LAUNCH_TYPE_GAME (100) for arg 4", () => {
      // Cyberpunk 2077 — a well-known Proton title
      expect(launchTypeFor(1091500)).toBe(LAUNCH_TYPE_GAME);
    });

    it("non-Steam shortcut gets LAUNCH_TYPE_SHORTCUT (104) for arg 4", () => {
      // Realistic appId generated by Steam for a non-Steam shortcut.
      // Steam generates these via CRC32 of the exe path, always >= 0x80000000.
      const realisticShortcutId = 0x80000000 + 0x1a2b3c; // 2 148 718 652
      expect(launchTypeFor(realisticShortcutId)).toBe(LAUNCH_TYPE_SHORTCUT);
    });

    it("boundary: last Steam appId (0x7FFFFFFF) → LAUNCH_TYPE_GAME", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD - 1)).toBe(LAUNCH_TYPE_GAME);
    });

    it("boundary: first non-Steam appId (0x80000000) → LAUNCH_TYPE_SHORTCUT", () => {
      expect(launchTypeFor(NON_STEAM_APPID_THRESHOLD)).toBe(LAUNCH_TYPE_SHORTCUT);
    });
  });
});

// ------------------------------------------------------------------ //
// toUnsignedAppId                                                      //
// ------------------------------------------------------------------ //

describe("toUnsignedAppId", () => {
  describe("values already in uint32 range are returned unchanged", () => {
    const noops: [string, number][] = [
      ["zero", 0],
      ["Half-Life 2 (220)", 220],
      ["Cyberpunk 2077 (1091500)", 1091500],
      ["max int32 (0x7FFFFFFF)", 0x7fffffff],
      ["first uint32 high bit (0x80000000)", 0x80000000],
      ["near-max uint32 (0xFFFFFF00)", 0xffffff00],
      ["max uint32 (0xFFFFFFFF)", 0xffffffff],
    ];

    it.each(noops)("%s – appId %i", (_name, appId) => {
      expect(toUnsignedAppId(appId)).toBe(appId);
    });
  });

  describe("signed-negative inputs are normalised to their uint32 bit pattern", () => {
    // Steam surfaces uint32 non-Steam shortcut appIds as signed int32s
    // in some code paths.  These tests assert that the bit pattern is
    // preserved: negative values map to their unsigned counterpart.
    const pairs: [string, number, number][] = [
      ["-1 → 0xFFFFFFFF", -1, 0xffffffff],
      ["-2 → 0xFFFFFFFE", -2, 0xfffffffe],
      ["-0x80000000 → 0x80000000 (threshold)", -0x80000000, 0x80000000],
      [
        "realistic signed non-Steam shortcut",
        -0x7fdeadbe /* int32 bit pattern of uint32 0x80215442 */,
        0x80215442,
      ],
    ];

    it.each(pairs)("%s", (_name, raw, expected) => {
      expect(toUnsignedAppId(raw)).toBe(expected);
    });
  });

  describe("degenerate inputs are passed through unchanged", () => {
    // Non-finite / non-number inputs are out-of-contract but should not
    // throw.  We return them as-is so the caller can log a warning
    // rather than inherit a silent NaN/0 downstream.
    it("NaN passes through as NaN", () => {
      expect(Number.isNaN(toUnsignedAppId(Number.NaN))).toBe(true);
    });

    it("Infinity passes through as Infinity", () => {
      expect(toUnsignedAppId(Number.POSITIVE_INFINITY)).toBe(Number.POSITIVE_INFINITY);
    });
  });
});

// ------------------------------------------------------------------ //
// isNonSteamShortcut / launchTypeFor — signed-int32 inputs             //
// ------------------------------------------------------------------ //

describe("isNonSteamShortcut with signed-int32 inputs (int-overflow)", () => {
  // These cover the Steam internals path where a uint32 appId >= 0x80000000
  // is surfaced as a signed-negative JS number because the C++ producer
  // typed the value as int32.  Without normalisation the `>= threshold`
  // check would incorrectly classify these as Steam games (launchType 100)
  // and RunGame would be invoked with the wrong arguments.

  it("−1 (int32 view of 0xFFFFFFFF) is a non-Steam shortcut", () => {
    expect(isNonSteamShortcut(-1)).toBe(true);
  });

  it("−0x80000000 (int32 view of 0x80000000 = threshold) is a non-Steam shortcut", () => {
    expect(isNonSteamShortcut(-0x80000000)).toBe(true);
  });

  it("a realistic signed-non-Steam appId is classified as non-Steam shortcut", () => {
    // int32 bit pattern of uint32 0x80215442 (a plausible shortcut id)
    expect(isNonSteamShortcut(-0x7fdeadbe)).toBe(true);
  });

  it("positive Steam game appId is still classified as a Steam game", () => {
    // Regression guard: normalising must not flip positive values.
    expect(isNonSteamShortcut(1091500)).toBe(false);
  });
});

describe("launchTypeFor with signed-int32 inputs (int-overflow)", () => {
  it("−1 → LAUNCH_TYPE_SHORTCUT (104)", () => {
    expect(launchTypeFor(-1)).toBe(LAUNCH_TYPE_SHORTCUT);
  });

  it("−0x80000000 → LAUNCH_TYPE_SHORTCUT (104)", () => {
    expect(launchTypeFor(-0x80000000)).toBe(LAUNCH_TYPE_SHORTCUT);
  });

  it("realistic signed non-Steam appId → LAUNCH_TYPE_SHORTCUT (104)", () => {
    expect(launchTypeFor(-0x7fdeadbe)).toBe(LAUNCH_TYPE_SHORTCUT);
  });

  it("positive Steam game appId is still LAUNCH_TYPE_GAME (100)", () => {
    expect(launchTypeFor(1091500)).toBe(LAUNCH_TYPE_GAME);
  });
});
